### ISSUE TITLE
Error while extracting the frames for some videos 

### ISSUE THREAD

**Issue by aminebdj** [OpenDriveLab/DriveAGI#16]
Dear authors,

Thanks a lot for your work,

I am facing some issues while extracting some videos that are downloaded. I am getting the following error.

```
File "<path>/DriveAGI/opendv/utils/frame_extraction.py", line 41, in extract_frames
    cv2_extract_frames(video_path, output_dir, fps, discard_begin, discard_end, exception_file)
  File "<path>/DriveAGI/opendv/utils/frame_extraction.py", line 145, in cv2_extract_frames
    num_frames = int( fps * (video.get(7) // video_fps - discard_begin - discard_end) )
ZeroDivisionError: float floor division by zero
Traceback (most recent call last):
  File "<path>/DriveAGI/opendv/utils/frame_extraction.py", line 41, in extract_frames
    cv2_extract_frames(video_path, output_dir, fps, discard_begin, discard_end, exception_file)
  File "<path>/DriveAGI/opendv/utils/frame_extraction.py", line 145, in cv2_extract_frames
    num_frames = int( fps * (video.get(7) // video_fps - discard_begin - discard_end) )
ZeroDivisionError: float floor division by zero
```

There are the videos saved in the exception file

```
{
    "video_path": "OpenDV-YouTube/videos/Road_Therapy/-G92wLAhsWk.mp4",
    "problem": "float floor division by zero",
    "action": "skipped",
    "details": "Traceback (most recent call last):\n  File \"<path>/DriveAGI/opendv/utils/frame_extraction.py\", line 41, in extract_frames\n    cv2_extract_frames(video_path, output_dir, fps, discard_begin, discard_end, exception_file)\n  File \"<path>/DriveAGI/opendv/utils/frame_extraction.py\", line 145, in cv2_extract_frames\n    num_frames = int( fps * (video.get(7) // video_fps - discard_begin - discard_end) )\nZeroDivisionError: float floor division by zero\n"
},
{
    "video_path": "OpenDV-YouTube/videos/takemytripdotcom/-GrFwuiFqbc.mp4",
    "problem": "float floor division by zero",
    "action": "skipped",
    "details": "Traceback (most recent call last):\n  File \"<path>/DriveAGI/opendv/utils/frame_extraction.py\", line 41, in extract_frames\n    cv2_extract_frames(video_path, output_dir, fps, discard_begin, discard_end, exception_file)\n  File \"<path>/DriveAGI/opendv/utils/frame_extraction.py\", line 145, in cv2_extract_frames\n    num_frames = int( fps * (video.get(7) // video_fps - discard_begin - discard_end) )\nZeroDivisionError: float floor division by zero\n"
},
{
    "video_path": "OpenDV-YouTube/videos/Walk_East/-X_lyIV76Ek.mp4",
    "problem": "float floor division by zero",
    "action": "skipped",
    "details": "Traceback (most recent call last):\n  File \"<path>/DriveAGI/opendv/utils/frame_extraction.py\", line 41, in extract_frames\n    cv2_extract_frames(video_path, output_dir, fps, discard_begin, discard_end, exception_file)\n  File \"<path>/DriveAGI/opendv/utils/frame_extraction.py\", line 145, in cv2_extract_frames\n    num_frames = int( fps * (video.get(7) // video_fps - discard_begin - discard_end) )\nZeroDivisionError: float floor division by zero\n"
},
.
.
.
```

All videos seem to have the .mp4 format, did you face this issue while extracting as well?

Many thanks

**Comment by GihhArwtw** [comment]
hi @aminebdj 
sorry for the late response.
I have already reproduced the issue you reported and am working on it. I'll keep you updated if I found the solution.

**Comment by GihhArwtw** [comment]
hi @aminebdj 
We just updated a version to get the frame rate from `ffmpeg` when `cv2` is not working. 
For details, you can refer to [implementation details](https://github.com/OpenDriveLab/DriveAGI/blob/main/opendv/utils/download.py#L10).

**NOTE: You need to use `ffmpeg<=3.4`, otherwise fragmented metadata may not be handled successfully.**
