### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by chaoqunwangcs** [OpenDriveLab/DriveAGI#9]
Thanks for the great job!
I would like to download the YouTube data with the given script, but the download command "youtube-dl -f {args} {url}" is not working, and the error infos is "ERROR: Unable to extract uploader id". Can you provide another downloading script? or are there any questions? A solution is using the 'yt-dlp' package, but I wonder about the downloading args, such as the resolution and ext， which is about the image quality and dataset size.

**Comment by YTEP-ZHI** [comment]
Hi @chaoqunwangcs, thanks for your feedback. This issue arises when YouTubers delete or make their videos private, thus these video links will be invalid. One solution is to skip these missing videos and we will update the code soon.

**Comment by chaoqunwangcs** [comment]
Thanks for your reply. But the issue is not because the YouTubers delete or make their videos private, as the 'yt-dlp' package could successfully download the video. To align with your datasets downloaded by the 'youtube-dl' package, I'd like to ask for the details such as the resolutions and ext, which is about the image quality and dataset scale.

**Comment by GihhArwtw** [comment]
Hi @chaoqunwangcs could you please give more information about the video that leads to `ERROR: Unable to extract uploader id`? (video_id or url) that'll help us handle the issue faster.

as for resolution and ext, most videos are downloaded at 1080p (720p for those that couldn't find a version at 1080p). As for ext, all videos are either in `mp4` format or `webm` format.

**Comment by GihhArwtw** [comment]
1. it seems that the command works fine on our server. Maybe the issue has something to do with the network condition?
Since `yt-dlp` package will work find on your end, I think I can update another download script using `yt-dlp`.

2. though many videos support 2K or 4K resolution, we still download their 1080p versions since the processed data will take up a lot of disk space. But of course you can download videos at higher resolution if you need.

**Comment by GihhArwtw** [comment]
hi @chaoqunwangcs. I just update the download script.

To download videos using `yt-dlp`, you just need to change the `method` configure in `configs/download.json` to `yt-dlp`. Please let us know if there are some further problems.

**Comment by makolon** [comment]
Hi @GihhArwtw,

I encountered an issue while trying to download videos using `yt-dlp`. After installing `yt-dlp` via the pip command and configuring it as the download method, I received the following error and warning:
```
"""
Traceback (most recent call last):
  File "/root/DriveAGI/opendv/scripts/youtube_download.py", line 36, in single_download
    raise Exception("ERROR: Video unavailable or network error.")
Exception: ERROR: Video unavailable or network error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/DriveAGI/opendv/scripts/youtube_download.py", line 39, in single_download
    with open(CONFIGS.exception_file, "a") as f:
AttributeError: 'EasyDict' object has no attribute 'exception_file'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/DriveAGI/opendv/scripts/youtube_download.py", line 102, in <module>
    multiple_download(video_list, configs)
  File "/root/DriveAGI/opendv/scripts/youtube_download.py", line 56, in multiple_download
    for _ in tqdm(p.imap(single_download, video_list), total=video_count):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
AttributeError: 'EasyDict' object has no attribute 'exception_file'
```

Could you please help me resolve this issue? Any assistance would be greatly appreciated.

Thank you!

**Comment by GihhArwtw** [comment]
the message says the corresponding video is no longer available. Since some uploaders might delete their channels or change their public videos to private, some videos can no longer be downloaded.

But i think i already made the script to skip these videos. Could you kindly tell me whether the download process will continue when you got these messages?

> p.s. the `EasyDict`-related error is a bug. i'll try to fix it today.

**Comment by makolon** [comment]
Thanks for your reply!!!
I initially thought that the process was stuck at the WARNING, but it actually continued!
However, an error about being unable to rename is output. Is it safe to ignore this error?
```
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/USA_Thrill/B1rC5Ni8Dgk.webm.part' -> 'OpenDV-YouTube/videos/USA_Thrill/B1rC5Ni8Dgk.webm'
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/J_Utah/Arz8k37-9F4.webm.part' -> 'OpenDV-YouTube/videos/J_Utah/Arz8k37-9F4.webm'
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/Relaxing_Walks/BWAbBu7uNdA.webm.part' -> 'OpenDV-YouTube/videos/Relaxing_Walks/BWAbBu7uNdA.webm'
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/Zhejiang_Street_Scenes/A8DZaOwQQ8U.webm.part' -> 'OpenDV-YouTube/videos/Zhejiang_Street_Scenes/A8DZaOwQQ8U.webm'
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/Relaxing_Walks/A_cPQJt-id4.webm.part' -> 'OpenDV-YouTube/videos/Relaxing_Walks/A_cPQJt-id4.webm'
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/The_Driving_Channel/AoXyxEi09CI.webm.part' -> 'OpenDV-YouTube/videos/The_Driving_Channel/AoXyxEi09CI.webm'
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/Relaxing_Scenes_-_Driving/CBtT-zVekxg.webm.part' -> 'OpenDV-YouTube/videos/Relaxing_Scenes_-_Driving/CBtT-zVekxg.webm'
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/Relaxing_Walks/BDXHtLqFUf4.webm.part' -> 'OpenDV-YouTube/videos/Relaxing_Walks/BDXHtLqFUf4.webm'
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/J_Utah/A0F1ZKqmavc.webm.part' -> 'OpenDV-YouTube/videos/J_Utah/A0F1ZKqmavc.webm'
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/Driving_in_China/BN2hmwUJH9o.webm.part' -> 'OpenDV-YouTube/videos/Driving_in_China/BN2hmwUJH9o.webm'
ERROR: Unable to rename file: [Errno 2] No such file or directory: 'OpenDV-YouTube/videos/Wheels_Around_The_World/BHm7wQ8Y_cU.webm.part' -> 'OpenDV-YouTube/videos/Wheels_Around_The_World/BHm7wQ8Y_cU.webm'

```

**Comment by GihhArwtw** [comment]
i'll look into it.
also, i'll fix the `EasyDict` bug today. i don't how i missed it before, probably since the testing download process can continue with the error message 😂

**Comment by GihhArwtw** [comment]
hi @makolon i just fix the `EasyDict` bug.
still, i could not reproduce the error you reported in the latter comment. But i think **it is not safe to ignore it**. Both `youtube-dl` and `yt-dlp` need to rename `*.part` (the temporary file) to `*.<EXT>` when they finished downloading.

**Comment by makolon** [comment]
hi @GihhArwtw!
Thank you! After pulling the revised code and running it again, it seems like the download was successful!
